[project]
name = "mcp-camsnap"
version = "0.1.0"
dependencies = [
    "mcp",
]

[project.scripts]
# Qui diciamo: l'eseguibile 'mcp-camsnap' deve cercare 
# nel file 'mcp_camsnap.py' la funzione 'main'
mcp-camsnap = "mcp_camsnap:main"

[tool.setuptools]
# Fondamentale: dice a setuptools che il file mcp_camsnap.py Ã¨ il modulo da includere
py-modules = ["mcp_camsnap"]