[project]
name = "mcp-camsnap"
version = "0.1.0"
dependencies = [
    "mcp",
]

[project.scripts]
# Questo dice: lancia il comando 'mcp-camsnap' eseguendo la funzione 'main' 
# dentro il file 'mcp_camsnap.py'
mcp-camsnap = "mcp_camsnap:main"

[tool.setuptools]
py-modules = ["mcp_camsnap"]