[project]
name = "mcp-camsnap"
version = "0.1.0"
dependencies = [
    "mcp",
]

[project.scripts]
# Nome eseguibile = "nome_file_python_senza_estensione:nome_funzione"
mcp-camsnap = "mcp_camsnap:main"